services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    queue_client_adapter_priority_handler:
        class: "%queue_client.adapter.priority_handler.class%"

    ReputationVIP\Bundle\QueueClientBundle\QueueClientAdapterFactory: ~

    ReputationVIP\Bundle\QueueClientBundle\QueueClientFactory: ~

    ReputationVIP\QueueClient\Adapter\AbstractAdapter:
        factory: ['@ReputationVIP\Bundle\QueueClientBundle\QueueClientAdapterFactory', get]
        arguments:
            $config: "%queue_client.config%"
            $priorityHandler: "@queue_client_adapter_priority_handler"

    ReputationVIP\QueueClient\QueueClient:
        factory: ['@ReputationVIP\Bundle\QueueClientBundle\QueueClientFactory', get]
        arguments:
            $container: '@service_container'
            $adapter: '@ReputationVIP\QueueClient\Adapter\AbstractAdapter'
            $queuesFile: '%queue_client.queues_file%'

    ReputationVIP\QueueClient\QueueClientInterface: '@ReputationVIP\QueueClient\QueueClient'

    ReputationVIP\Bundle\QueueClientBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
